### ISSUE TITLE
Participants Solution submissions

### ISSUE THREAD

**Issue by GuillermoAbadLopez** [qiskit-community/qgss-2024#12]
Hello @vabarbosa,

I would like to submit my solutions for `lab_1`, `lab_2` and `lab_4`. 
Do you think that is going to be possible? Would you like it?
(Like in: https://github.com/qiskit-community/ibm-quantum-challenge-2024)

Looking forward to hear from you,
Guillermo Abad

**Comment by vabarbosa** [comment]
hello @GuillermoAbadLopez thank you. i will check with the team if they will be collecting participant solutions for this event and follow up with you.

**Comment by vabarbosa** [comment]
@GuillermoAbadLopez i have added a [folder for participants to submit their solutions](https://github.com/qiskit-community/qgss-2024/tree/main/solutions_from_participants). please feel free to open a PR and submit your solutions there. thank you again!

**Comment by GuillermoAbadLopez** [comment]
@vabarbosa that is great news! 

Just created a PR with my solutions here:  https://github.com/qiskit-community/qgss-2024/pull/14!
