### ISSUE TITLE
Another Lab 4 file

### ISSUE THREAD

**Issue by mlowe308** [qiskit-community/qgss-2024#17]
I completed Lab 4 and am submitting my graphs for the last problem involving 50 spin qubits.

**Comment by mlowe308** [comment]
How do I submit my file?

**Comment by vabarbosa** [comment]
hi @mlowe308 you will need to 

1. fork this repository
1. add your files
1. submit a pull request

additional info if you are not too familiar with github: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by vabarbosa** [comment]
Resolved by https://github.com/qiskit-community/qgss-2024/pull/18
